# Generated by Django 5.0.4 on 2024-05-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_rut'),
        ('core', '0003_auto_20240505_2036'),
    ]

    operations = [
    ]
